# Generated by Django 4.0.4 on 2022-05-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='Номер машины')),
                ('car_color', models.CharField(max_length=32, verbose_name='Цвет машины')),
                ('car_brand', models.CharField(max_length=32, verbose_name='Бренд машины')),
                ('car_type', models.IntegerField(choices=[(1, 'Седан'), (2, 'Универсал'), (3, 'Хетчбэк'), (4, 'Лифтбэк'), (5, 'Лимузин'), (6, 'Пикап'), (7, 'Минивэн'), (8, 'Купе'), (9, 'Четырёхдверное купе'), (10, 'Масл кар'), (11, 'Кабриолет'), (12, 'Фаэтон'), (13, 'Ландо'), (14, 'Кроссовер'), (15, 'Родстер'), (16, 'Внедорожник')], verbose_name='Тип машины')),
                ('is_sell_now', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания машины')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обновления машины')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
