# Generated by Django 4.0.4 on 2022-05-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_car_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, unique=True, upload_to='back/uploads', verbose_name='Изображение машины'),
        ),
    ]
