# Generated by Django 4.0.4 on 2022-05-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_car_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_price',
            field=models.FloatField(default=0, verbose_name='Цена машины'),
        ),
    ]
